### ISSUE TITLE
Mutual TLS Authentication support

### ISSUE THREAD

**Issue by DmitriExpedia** [ExpediaGroup/styx#124]
## The problem
We have clients that require mutual authentication https://en.wikipedia.org/wiki/Mutual_authentication while connecting over internet. 

## Detailed description
Styx does not support that feature at that time.

## Acceptance criteria
- We should be able to upload client certs / root + intermediate certs on the Styx server and should be able to force client certificate verification. 
- Ideally verification could be either required = client has to provide valid cert otherwise 400 http code will be returned back. Or optional = ask client for a cert and let the request to proceed if there is no cert provided. It would be an analogue to ON and OPTIONAL options http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_verify_client
- Be able to include client cert details on the request to a downstream service (http headers for example)

**Comment by kvosper** [comment]
Closing all issues over 3 years old. New issues can be created if problems are still occurring.
