### ISSUE TITLE
Evaluate the use of netty's NameResolver and DnsCache instead of InetAddress classes.

### ISSUE THREAD

**Issue by dvlato** [ExpediaGroup/styx#154]
## The problem
The DNS caching solution in Java is flawed as it does not respect the TTL settings. It could also benefit from alternating the IP addresses in a round robin fashion. 

Netty added in 4.1  the interfaces [NameResolver](https://netty.io/4.1/api/io/netty/resolver/NameResolver.html) and [DnsCache](https://netty.io/4.1/api/io/netty/resolver/dns/DnsCache.html)  (which are marked as **unstable** ) to provide its own implementation for hostname resolution that should fix these issues.  

It seems worth exploring migrating our DNS resolution code to use those classes so Styx doesn't have to rely on performing the actual DNS requests (which can be costly) each time when we need to connect to a pool of servers behind a single host name .

**Comment by kvosper** [comment]
Closing all issues over 3 years old. New issues can be created if problems are still occurring.
