### ISSUE TITLE
Introduce admin endpoint to expose the server status

### ISSUE THREAD

**Issue by ggaeta1** [ExpediaGroup/styx#317]
## The problem
I am not able to understand when the server is ready. The workaround that I used is based on finding a string in the logs 

## Detailed description
Introduce an admin endpoint to retrieve the server status

**Comment by bestokes** [comment]
Please review after implementation of the routing object model. @mikkokar

**Comment by kvosper** [comment]
Closing all issues over 3 years old. New issues can be created if problems are still occurring.
