### ISSUE TITLE
Sensible defaults for Styx backend TLS settings.

### ISSUE THREAD

**Issue by mikkokar** [ExpediaGroup/styx#32]
## The problem

Enabling TLS for backend services doesn't work out of the box. Styx insist that trust store is specified (`tlsSetings.trustStorePath`), even if it would not be used. This is quite burdensome as an empty trust store must be created just for the sake of establishing a TLS connection to backends.

## Detailed description

Styx should be more in line with default Java behaviour as described in [JSSE Reference Guide](https://docs.oracle.com/javase/8/docs/technotes/guides/security/jsse/JSSERefGuide.html#CustomizingStores):

* When `trustStorePath` is absent, Styx should use a trust store specified by `javax.net.ssl.trustStore` system property.

* When `trustStorePath` is absent, and `javax.net.ssl.trustStore` is not set, then use the default system truststore. This would be, for JDK provider, `$JAVA_HOME/lib/security/jssecacerts`, or `$JAVA_HOME/lib/security/cacerts`.

## Acceptance criteria

* Styx will start up with the following `tlsSettings` configuration, and either use the truststore configured via `javax.net.ssl.trustStore` system property, or alternatively revert to default keystore.

```
    - id: "tls11"
      path: "/v11"
      tlsSettings:
        trustAllCerts:       true
        sslProvider:         OPENSSL     # Also supports JDK
      origins:
      - { id: "app1", host: "mybackend:443" }
```

**Comment by kvosper** [comment]
Closing all issues over 3 years old. New issues can be created if problems are still occurring.
