### ISSUE TITLE
Log a warning message when message content cannot be determined

### ISSUE THREAD

**Issue by bestokes** [ExpediaGroup/styx#385]
To improve the experience of software engineers, Styx should log a warning message when it cannot determine the content length of the proxied message. This is so that we can get an instant clue on what is going wrong without having to consult styx developers.

When styx receives a non-chunked message without content-length header, it it cannot determine when to finish proxying the message. This then leads into undesirable side effects, such as Styx closing channels due to HTTP content timers, etc. Resulting a bunch of error messages that do not obviously point to the root cause.

For example, proxying a HTTP response, the TCP connection towards origins will be closed, triggering a TCP connection closure on the proxy side. This may then result in Netty write errors for the response message.

The request side needs to be tested too, to find out the side effects when the request length cannot be determined.

**Comment by kvosper** [comment]
Closing all issues over 3 years old. New issues can be created if problems are still occurring.
