### ISSUE TITLE
Deprecate styx test-api.

### ISSUE THREAD

**Issue by mikkokar** [ExpediaGroup/styx#456]
I believe styx test API can be deprecated because everybody is using the StyxServer class from the proxy project anyway.

This is a `styx-test-api` project.

Relates to: #177

**Comment by manishsahni2000** [comment]
Hi,

Will be picking up this task

**Comment by mikkokar** [comment]
> Hi,
> 
> Will be picking up this task

Thanks Manish, that's great!

**Comment by mikkokar** [comment]
This task involves removing the `styx-test-api` maven module. That is the `support/test-api` directory and all files under it, and fixing all code that refers to it.

**Comment by kvosper** [comment]
Closing all issues over 3 years old. New issues can be created if problems are still occurring.
