### ISSUE TITLE
pendingConnectionsCount=50 is greater than maxPendingConnectionsPerHost=50

### ISSUE THREAD

**Issue by mcucchiara** [ExpediaGroup/styx#490]
shouldn't be "pendingConnectionsCount=51 is greater than maxPendingConnectionsPerHost=50"

https://github.com/HotelsDotCom/styx/blob/24e85648ae31249016611278e454ed1e17d834f0/components/client/src/main/java/com/hotels/styx/client/connectionpool/SimpleConnectionPool.java#L86-L89

https://github.com/HotelsDotCom/styx/blob/b66971a9fa3c07df3176967e0481d228abc69c68/components/client/src/main/java/com/hotels/styx/client/connectionpool/MaxPendingConnectionsExceededException.java#L31-L33

Happy to raise a PR

**Comment by ploutarchos** [comment]
@mcucchiara I would actually suggest logging the `waitingSubscribers.size()` which will be +1 or potentially more.

**Comment by mikkokar** [comment]
Hi @mcucchiara are you saying pending connections count sometimes exceeds the maximum? Have you identified the issue and have a fix available, then please by all means send a PR.

**Comment by mikkokar** [comment]
@OwenLindsell could you look at this too?

**Comment by kvosper** [comment]
Closing all issues over 3 years old. New issues can be created if problems are still occurring.
