### ISSUE TITLE
A page to display routing objects in a tabular format

### ISSUE THREAD

**Issue by mikkokar** [ExpediaGroup/styx#517]
Implement a HTML page showing all routing objects in a tabular format.

This page should be conceptually similar to https://github.com/HotelsDotCom/styx/pull/503, but more generic. It should show each routing object in the database:

- Routing object name, type, tags, and possibly its configuration.

**Comment by kvosper** [comment]
Closing all issues over 3 years old. New issues can be created if problems are still occurring.
