### ISSUE TITLE
Remove HTML rendering from YamlFileConfigurationService

### ISSUE THREAD

**Issue by mikkokar** [ExpediaGroup/styx#649]
Replace YamlFileConfigurationService HTML rendering with yaml or json output format.

Continuation of #605 

Rationale:

* Simplifies codebase: A possibility to eliminate an extra library.
* Simplifies codebase: No need to bundle the static assets.
* Eases bug reporting and investigation: Easier for users to send an YAML or JSON file along with bug reports than an HTML page. Also easier for styx core developers to consume it in this format.

Acceptance Criteria:

* Remove `assets` endpoint from `YamlFileConfigurationService`.
* `OriginsPageRenderer` class returns an Yaml or JSON format. Or even better returns whichever format an user agent requested.
* Drop the `kotlinx-html-jvm` dependency (unless used for something else).

**Comment by kvosper** [comment]
Closing all issues over 3 years old. New issues can be created if problems are still occurring.
