### ISSUE TITLE
Replace Dropwizard metrics with Micrometer metrics

### ISSUE THREAD

**Issue by chrisgresty** [ExpediaGroup/styx#664]
Styx metrics are currently based on Dropwizard/Codahale, and are only reported to one type of metrics service - Graphite. These metrics have no support for useful features such as tagging.

Micrometer (http://micrometer.io) provides a metrics facade, in a similar way that SLF4J does for logging, that can support different metrics providers.

Styx metrics should be migrated to use Micrometer instead of Dropwizard. This will allow Styx to use more advanced metrics features, remove the current dependency on Graphite and provide support for whatever metrics service is required.

**Comment by kvosper** [comment]
This has been implemented a long time ago.
