### ISSUE TITLE
after unzipped, it cannot run with default.yml,even after several error is fixed.

### ISSUE THREAD

**Issue by autoappcreator** [ExpediaGroup/styx#719]
11:27:48.649 [main] ERROR com.hotels.styx.StyxServer - Styx server failed to start due to configuration error in file [D:\workspace\styx\distribution\.\conf\default.yml]: Unexpected field type. Field 'routingObjects[h2Handler].config' should be OBJECT(status, content, headers), but it is NULL

**Comment by guoxiaodonggit** [comment]
same error
