### ISSUE TITLE
make e2e failing

### ISSUE THREAD

**Issue by ryanellison** [ExpediaGroup/styx#788]
Running make e2e currently fails against the master branch with the following error:
```
[ERROR] Failed to execute goal org.jacoco:jacoco-maven-plugin:0.8.5:report (report) on project styx-api: An error has occurred in JaCoCo report generation.: Error while creating report: Error while analyzing ... styx/components/api/target/classes/com/hotels/styx/api/extension/service/spi/RegistryChangesKt.class. Unexpected SMAP line: *S KotlinDebug -> [Help 1]
```
This seems to be fixable by bumping jacoco-maven-plugin up to version 0.8.7. However, this uncovers additional failures, including checkstyle issues and failing Scala tests.

This issue is to make all required changes for make e2e to run successfully.

**Comment by kvosper** [comment]
`make e2e` is currently working. Note: jacoco maven plugin version is `0.8.11`
